import logging, subprocess, sys
from pathlib import Path
from datetime import datetime
from jinja2 import Template
from markdown_it import MarkdownIt
from .config import REPORT_DIR, TEMPLATE_PATH

log = logging.getLogger(__name__)
_md = MarkdownIt()


def export(
    markdown_text: str,
    meeting_id: int,
    title: str = "Meeting",
    duration_min: float = 0,
    auto_open: bool = True,
) -> dict[str, Path]:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = f"mtg{meeting_id:04d}_{ts}"

    md_path = REPORT_DIR / f"{slug}.md"
    md_path.write_text(markdown_text, encoding="utf-8")

    html_body = _md.render(markdown_text)
    tmpl_text = TEMPLATE_PATH.read_text() if TEMPLATE_PATH.exists() else _DEFAULT_TMPL
    html = Template(tmpl_text).render(
        title=title,
        date=datetime.now().strftime("%d %b %Y %H:%M"),
        duration=f"{duration_min:.0f} min" if duration_min else "—",
        content=html_body,
        meeting_id=meeting_id,
    )
    html_path = REPORT_DIR / f"{slug}.html"
    html_path.write_text(html, encoding="utf-8")
    log.info(f"Report saved: {html_path}")

    if auto_open and sys.platform == "darwin":
        subprocess.run(["open", str(html_path)])
    return {"markdown": md_path, "html": html_path}


_DEFAULT_TMPL = """<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>{{ title }}</title><style>
body{background:#0d0f12;color:#e8eaf0;font-family:system-ui,sans-serif;
  max-width:900px;margin:2rem auto;padding:2rem;line-height:1.75}
h1{color:#8b7cf8}h2{color:#34d399;border-bottom:1px solid #1c2030;padding-bottom:.4rem;margin-top:2rem}
h3{color:#fbbf24}table{border-collapse:collapse;width:100%;margin:1rem 0;font-size:.9rem}
th{background:#1c2030;color:#9aa0b8;padding:.5rem .75rem;text-align:left;font-size:.75rem;
  text-transform:uppercase;letter-spacing:.05em}
td{padding:.55rem .75rem;border-bottom:1px solid #1c2030;vertical-align:top}
tr:hover td{background:#141720}code{background:#1c2030;border-radius:4px;padding:2px 6px}
pre{background:#141720;border-radius:8px;padding:1rem;overflow-x:auto}
blockquote{border-left:3px solid #8b7cf8;padding:.5rem 1rem;background:#141720;border-radius:0 8px 8px 0}
.meta{color:#5c6280;font-size:.82rem;margin-bottom:2rem}a{color:#60a5fa}
</style></head><body>
<h1>{{ title }}</h1><div class="meta">{{ date }} &middot; {{ duration }}</div>
{{ content }}<p style="color:#5c6280;font-size:.75rem;margin-top:3rem">
Generated by MeetingBot &middot; Local &middot; No data left this machine</p>
</body></html>"""
